# Assignment #2
I divided the work into two Markdown documents. "Exploratory_Analysis.md" includes the exploratory analysis of the data. "Plot_Gapminder.md" includes the various plots I've made.

## Exploratory_Analysis Process

Overall, coding to explore the dataset wasn't too difficult. The only trouble I really had was trying to use "knitr::kable", because it behaved very poorly when I was trying to make a frequency table for "country". This is probably because of the quantity of countries in the data.frame, but I was able to get it to work by looking it up on [Stack Overflow](https://stackoverflow.com/questions/31007915/print-a-frequency-table-of-a-factor-with-kable-in-rmarkdown). Otherwise, all of the other functions I am already familiar with (either from class or outside of class)

## Plot_Gapminder Process


## Additional Question

  filter(gapminder, country == c("Rwanda", "Afghanistan"))

The above code actually "fails", because it does not get every observation for "Rwanda" and "Afghanistan". Instead, because "country" and c("Rwanda", "Afghanistan") are vectors of different length. The second vector is copied multiple times to achieve the same length as the first vector (if possible), resulting in pairwise matching between "country" and c("Rwanda", "Afghanistan", "Rwanda", "Afghanistan", ......). Thus we end up with only a fraction of our desired data subset.

This was not the intent of the code. Instead, the proper way to go about getting all observations from Rwanda and Afghanistan is:

  filter(gapminder, country %in% c("Rwanda", "Afghanistan"))

This line of code checks each component of the vector (gapminder$country) to see if they exist within the vector of countries provided ("Rwanda" and "Afghanistan").

