---
title: "Gapminder Data Exploration"
author: "Nikolas Krstic"
date: "September 15, 2017"
output: github_document
keep_md: yes
---

##Exploring the gapminder dataset

```{r, echo=F, message=F}
library(tidyverse)
library(gapminder)
```

###The first few observations
```{r, echo=F}
head(gapminder)
```

###The last few observations
```{r, echo=F}
tail(gapminder)
```

###Dataset structure
```{r, echo=F}
str(gapminder)
```

###Summary statistics of the variables
```{r, echo=F}
summary(gapminder)
```

###Global Average Life Expectancy for 1952-2007 (5-year intervals)
```{r, echo=F, message=F, warning=F}
gapminder2 = aggregate(gapminder, by=list(gapminder$year), FUN=mean)
plot(gapminder2$year, gapminder2$lifeExp, ylab = "Life Expectancy", xlab="Year", col="red", pch=16)
```

###Global Average Gross Domestic Product (GDP) Per Capita for 1952-2007 (5-year intervals)
```{r, echo=F, message=F, warning=F}
gapminder2 = aggregate(gapminder, by=list(gapminder$year), FUN=mean)
plot(gapminder2$year, gapminder2$gdpPercap, ylab = "GDP per capita", xlab="Year", col="green", pch=16)
```

